"""
python manage.py set_websites
직접 조사한 공식 홈페이지 URL을 Place.website 에 저장합니다.
"""
from django.core.management.base import BaseCommand
from culture.models import Place

_ROYAL_TOMBS = 'https://royaltombs.cha.go.kr/'

WEBSITE_MAP = [
    # ── 궁궐 ─────────────────────────────────────────────────
    ('경복궁',   'https://royal.khs.go.kr/ROYAL/contents/menuInfo-gbg.do?grpCode=gbg'),
    ('창덕궁',   'https://royal.khs.go.kr/ROYAL/contents/menuInfo-gbg.do?grpCode=cdg'),
    ('창경궁',   'https://cgg.cha.go.kr/'),
    ('덕수궁',   'https://royal.khs.go.kr/ROYAL/contents/menuInfo-gbg.do?grpCode=dsg'),
    ('경희궁',   'https://royal.khs.go.kr/ROYAL/contents/R110000000.do'),
    ('사직단',   'https://royal.khs.go.kr/ROYAL/contents/menuInfo-sag.do?grpCode=sag'),
    ('종묘',     'https://jm.cha.go.kr/'),
    ('운현궁',   'https://www.unhyeongung.or.kr/'),
    # ── 조선왕릉 (궁능유적본부) ──────────────────────────────
    ('서삼릉',       _ROYAL_TOMBS),
    ('선릉과 정릉',  _ROYAL_TOMBS),
    ('태릉강릉',     _ROYAL_TOMBS),
    ('헌릉',         _ROYAL_TOMBS),
    ('파주 삼릉',    _ROYAL_TOMBS),
    ('파주 장릉',    _ROYAL_TOMBS),
    ('김포 장릉',    _ROYAL_TOMBS),
    ('온릉',         _ROYAL_TOMBS),
    ('융건릉',       _ROYAL_TOMBS),
    ('광릉',         _ROYAL_TOMBS),
    # ── 성곽·산성 ────────────────────────────────────────────
    ('수원화성',  'https://www.visitsuwon.or.kr/base/main/view'),
    ('화성행궁',  'https://www.suwon.go.kr/web/visitsuwon/hs02/pages.do'),
    ('남한산성',  'https://www.gg.go.kr/namhansansung-2/main.do'),
    ('행주산성',  'https://www.goyangsi.go.kr/culture/tour/tourDetail.do?sn=10112'),
    ('광화문',    'https://gwanghwamun.seoul.go.kr/'),
    ('흥인지문',  'https://www.jongno.go.kr/jongnolife/culture/heritageDetail.do?heritageId=13'),
    # ── 사찰 ─────────────────────────────────────────────────
    ('조계사',    'https://www.jogyesa.kr/'),
    ('봉은사',    'https://www.bongeunsa.org/'),
    ('진관사',    'https://www.jinkwansa.org/'),
    ('길상사',    'https://www.gilsangsa.or.kr/'),
    ('봉선사',    'https://www.bongsunsa.net/'),
    ('봉원사',    'https://www.bongwonsa.or.kr/'),
    ('도선사',    'https://doseonsa.org/'),
    ('용주사',    'https://www.yongjoosa.or.kr/'),
    ('신륵사',    'https://www.silleuksa.org/'),
    # ── 성지·성당 ────────────────────────────────────────────
    ('명동성당',         'https://www.mdsd.or.kr/'),
    ('서소문성지',       'https://www.seosomun.org/'),
    ('절두산',           'https://www.jeoldusan.or.kr/'),
    # ── 국립박물관·미술관 ─────────────────────────────────────
    ('국립중앙박물관',   'https://www.museum.go.kr/'),
    ('국립민속박물관',   'https://www.nfm.go.kr/'),
    ('국립고궁박물관',   'https://www.gogung.go.kr/'),
    ('국립한글박물관',   'https://www.hangeul.go.kr/'),
    ('국립현대미술관',   'https://www.mmca.go.kr/'),
    ('국립항공박물관',   'https://www.aviation.or.kr/'),
    ('대한민국역사박물관', 'https://www.much.go.kr/'),
    ('국립국악',         'https://www.gugak.go.kr/'),
    ('한성백제박물관',   'https://baekjemuseum.seoul.go.kr/'),
    ('전곡선사박물관',   'https://jgpm.ggcf.kr/'),
    ('실학박물관',       'https://silhak.ggcf.kr/'),
    ('한국만화박물관',   'https://www.komacon.kr/comicsmuseum/'),
    # ── 서울시립 박물관·미술관 ───────────────────────────────
    ('서울역사박물관',   'https://museum.seoul.go.kr/'),
    ('서울생활사박물관', 'https://museum.seoul.go.kr/slhm/'),
    ('서울시립미술관',   'https://sema.seoul.go.kr/'),
    ('서울공예박물관',   'https://craftmuseum.seoul.go.kr/'),
    ('서울식물원',       'https://botanicpark.seoul.go.kr/'),
    ('서울시립과학관',   'https://science.seoul.go.kr/'),
    # ── 경기도 박물관 ────────────────────────────────────────
    ('경기도박물관',       'https://musenet.ggcf.kr/'),
    ('경기도어린이박물관', 'https://gcm.ggcf.kr/'),
    ('수원시립미술관',     'https://suma.suwon.go.kr/'),
    ('화성박물관',         'https://smuseum.suwon.go.kr/hs/main/view'),
    ('추사박물관',         'https://www.gccity.go.kr/museum.do'),
    ('양주시립회암사지박물관', 'https://www.yangju.go.kr/museum/index.do'),
    ('남양주시립박물관',   'https://www.nyj.go.kr/museum/index.do'),
    # ── 기념관·역사관 ────────────────────────────────────────
    ('전쟁기념관',         'https://www.warmemo.or.kr/'),
    ('서대문형무소역사관', 'https://sphh.sscmc.or.kr/'),
    ('백범김구기념관',     'https://www.kimkoomuseum.org/'),
    ('전태일기념관',       'https://www.taeil.org/'),
    ('윤봉길',             'https://www.yunbonggil.or.kr/'),
    ('손기정기념관',       'https://www.sonkeechung.com/'),
    ('윤동주문학관',       'https://www.jfac.or.kr/site/main/content/yoondj01'),
    ('배재학당역사박물관', 'https://www.pcu.ac.kr/appenzeller'),
    ('국립4',              'https://www.mpva.go.kr/419/index.do'),
    ('국회박물관',         'https://museum.assembly.go.kr/museum/main/main.do'),
    ('안성 3·1운동기념관', 'https://www.anseong.go.kr/tourPortal/41/main.do'),
    # ── 유적지 ───────────────────────────────────────────────
    ('암사동',    'https://sunsa.gangdong.go.kr/'),
    ('한국민속촌', 'https://www.koreanfolk.co.kr/'),
    ('독립기념관', 'https://i815.or.kr/'),
    # ── 마을·거리 ────────────────────────────────────────────
    ('북촌한옥마을', 'https://hanok.seoul.go.kr/front/kor/town/town01.do'),
    ('남산골한옥마을', 'https://www.hanokmaeul.or.kr/'),
    ('은평한옥마을', 'https://hanok.seoul.go.kr/front/kor/town/town03.do'),
    ('인사동',       'https://www.insadong.info/'),
    # ── 수목원·공원 ──────────────────────────────────────────
    ('국립수목원',  'https://www.kna.go.kr/'),
    ('서울숲',      'https://seoulforest.or.kr/'),
    ('서울대공원',  'https://grandpark.seoul.go.kr/'),
    # ── 서울 사립박물관 ──────────────────────────────────────
    ('가회민화박물관',          'http://www.gahoemuseum.org/new/'),
    ('국립극장 공연예술박물관', 'https://www.ntok.go.kr/museum/main.do'),
    ('국립기상박물관',          'https://science.kma.go.kr/'),
    ('국립대한민국임시정부기념관', 'https://www.nmkpg.go.kr/'),
    ('근현대사기념관',          'http://mhmh.or.kr/'),
    ('김달진미술자료박물관',    'http://www.daljinmuseum.com/'),
    ('농업박물관',              'http://www.agrimuseum.or.kr/'),
    ('떡박물관',                'http://www.tkmuseum.or.kr/'),
    ('문화비축기지',            'https://parks.seoul.go.kr/template/sub/culturetank.do'),
    ('목인박물관',              'http://www.mokinmuseum.com/'),
    ('삼성출판박물관',          'http://ssmop.org/'),
    ('수도박물관',              'https://arisu.seoul.go.kr/arisumuseum/'),
    ('식민지역사박물관',        'https://historymuseum.or.kr/'),
    ('신문박물관',              'https://www.presseum.or.kr/'),
    ('세계장신구박물관',        'https://www.wjm.or.kr/'),
    ('외교사료관',              'https://diplomaticarchives.mofa.go.kr/new/main/'),
    ('우리옛돌박물관',          'http://koreanstonemuseum.com/'),
    ('우석뮤지엄',              'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=5fe7a480-c0de-4d6d-a949-e792d3c4d026'),
    ('우표박물관',              'https://stampmuseum.kr/'),
    ('유금와당박물관',          'http://yoogeum.org/'),
    ('은평역사한옥박물관',      'https://museum.ep.go.kr/'),
    ('이한열기념관',            'http://www.leememorial.or.kr/'),
    ('이화여대 자연사박물관',   'http://nhm.ewha.ac.kr/'),
    ('전기박물관',              'https://home.kepco.co.kr/kepco/EH/Main/main.do'),
    ('전쟁과여성인권박물관',    'https://womenandwarmuseum.net/'),
    ('짚풀생활사박물관',        'http://www.jipul.com/'),
    ('한국금융사박물관',        'https://www.beautifulshinhan.co.kr/'),
    ('한상수자수박물관',        'http://www.hansangsoo.co.kr/'),
    ('호림박물관',              'https://www.horimmuseum.org/ko'),
    ('피규어뮤지엄W',          'http://www.figuremuseumw.co.kr/'),
    ('고당기념관',              'http://godang.kr/'),
    ('경기여고 경운박물관',     'http://kwmuseum.org/'),
    ('북촌생활사박물관',        'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=86670eae-c868-46eb-b683-77836d42b92e'),
    # ── 경기 박물관·기념관 ──────────────────────────────────────
    ('경기도행정역사관',        'https://www.gg.go.kr/history/main.do'),
    ('국립6·25전쟁납북자기념관', 'https://www.abductions625.go.kr/'),
    ('국립지도박물관',          'https://www.ngii.go.kr/map/main.do'),
    ('덕포진교육박물관',        'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=e2742198-85f4-4bf5-bc22-b0d7f1952dd3'),
    ('두루뫼박물관',            'http://www.durumea.org/'),
    ('매향리평화역사관',        'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=9d1bb41b-4f99-4849-933e-33555ce4c8d4'),
    ('몽양여운형기념관',        'https://www.yp21.go.kr/museumhub/contents.do?key=954'),
    ('목아박물관',              'https://moka.or.kr/'),
    ('다도박물관',              'https://kimpodadomuseum.modoo.at/'),
    ('박물관 얼굴',             'http://visagej.org/'),
    ('서해수호관',              'https://wsph.navy.mil.kr/'),
    ('성호박물관',              'https://www.ansan.go.kr/seongho/main/main.do'),
    ('세미원 연꽃박물관',       'https://www.semiwon.or.kr/'),
    ('시흥오이도박물관',        'https://oidomuseum.siheung.go.kr/'),
    ('아해박물관',              'http://www.ahaemuseum.org/'),
    ('안산올림픽기념관',        'https://www.ansanuc.net/museum/index.do'),
    ('여성생활사박물관',        'https://womanlife.kr/'),
    ('여주시립폰박물관',        'https://www.yeoju.go.kr/phone/index.do'),
    ('예아리박물관',            'http://yearee.com/'),
    ('왈츠와 닥터만 커피박물관', 'http://www.wndcof.org/'),
    ('우석헌자연사박물관',      'https://www.geomuseum.org/'),
    ('잔아문학박물관',          'http://www.janamuseum.com/'),
    ('최용신기념관',            'https://www.ansan.go.kr/choiyongshin/main/main.do'),
    ('출판도시 활판인쇄박물관', 'http://www.letterpressmuseum.co.kr/'),
    ('충현박물관',              'http://www.chunghyeon.org/'),
    ('판교박물관',              'https://museum.seongnam.go.kr/pangyo/'),
    ('펄벅기념관',              'https://www.bcmuseum.or.kr/ko/'),
    ('풀짚공예박물관',          'http://www.pulzip.com/'),
    ('하남역사박물관',          'https://www.hanammuseum.com/'),
    ('한과문화박물관 한가원',   'http://hangaone.com/'),
    ('한국근현대사박물관',      'http://www.kmhm.or.kr/'),
    ('한국기독교역사박물관',    'http://www.kchmuseum.org/'),
    ('한국조리박물관',          'https://moca-museum.co.kr/'),
    ('한국카메라박물관',        'http://www.kcpm.or.kr/'),
    ('화성시 향토박물관',       'https://hsmuseum.hscity.go.kr/'),
    ('수원광교박물관',          'https://smuseum.suwon.go.kr/gg/main/view'),
    ('용인시박물관',            'https://www.yongin.go.kr/museum/index.do'),
    # ── 사찰 (추가) ──────────────────────────────────────────
    ('백련사(서대문)',   'http://www.paengryontemple.or.kr/'),
    ('백련사(가평)',     'http://www.baekryunsa.com/'),
    ('관문사(서울)',     'https://www.gwanmunsa.org/'),
    ('금선사(서울)',     'http://www.geumsunsa.org/'),
    ('극락사(서울)',     'http://kukraksa.com/'),
    ('보광사(과천)',     'http://www.bokwangsa.net/'),
    ('보문사(서울)',     'http://www.bomunsa.or.kr/'),
    ('불암사(남양주)',   'http://www.bulamsa.com/'),
    ('수종사',          'http://sujongsa.net/'),
    ('연주암',          'http://www.yeonjuam.or.kr/'),
    ('천축사(서울)',     'http://www.cheonchuksa.kr/'),
    ('흥국사(고양)',     'http://www.heungguksa.or.kr/'),
    # ── 역사유적·성지·성당 ──────────────────────────────────────
    ('가회동성당',              'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=3f2ef750-b27f-4ee8-bc59-811c92b7667c'),
    ('건청궁',                  'https://www.royalpalace.go.kr/content/data/data_03_11.asp'),
    ('광주 조선백자 요지',      'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=c7572870-4bfb-4903-b003-a41263f31281'),
    ('독립문',                  'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=0ee35368-8cac-464f-b351-433e6fdfc0f2'),
    ('대한성공회 서울주교좌성당', 'https://www.cathedral.or.kr/'),
    ('도봉서원',                'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=b45b20c9-5d28-4777-a676-da2ab5b17f97'),
    ('명성황후 생가',           'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=5745913a-88cf-4cfa-923d-006f438c41f7'),
    ('몽촌토성',                'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=93eb3111-2ad1-48e4-a957-eec31a6550fb'),
    ('백인제가옥',              'https://museum.seoul.go.kr/www/intro/annexIntro/annex_22/annex_22_01.jsp'),
    ('서울 경교장',             'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=cb8a445f-6bc1-4d03-99d5-0c6191a26da8'),
    ('서울 살곶이 다리',        'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=d845a63f-390c-4568-ab32-a94d8838f017'),
    ('서울 삼전도비',           'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=1fd93e30-e92c-4198-96b1-20b34f06a45c'),
    ('서울 약현성당',           'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=fefaaf63-5cfb-4cc4-ae2c-891188e2a95b'),
    ('서울 우정총국',           'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=9b3a6975-ecc6-4261-948d-8626903ff9d3'),
    ('서울 풍납동 토성',        'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=f79a12ce-8695-475c-abc7-47b6b6315976'),
    ('성균관 명륜당',           'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=b83a929f-a6c4-417c-991c-d8e01fe63b57'),
    ('화령전',                  'https://www.visitsuwon.or.kr/base/main/view'),
    ('숭례문',                  'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=6a9fe3f5-7a55-48f1-a429-6aaf57584c36'),
    ('양주 회암사지',           'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=892c6e58-3d07-414e-b185-54ab788dfbfe'),
    ('호로고루',                'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=19c090e9-3a91-4bf7-9d3d-aa37eaaff273'),
    ('여주 고달사지',           'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=0a99c5d5-fb10-422a-9f51-2222818c4438'),
    ('여주 파사성',             'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=de27c04e-5990-42ca-8c4f-31adcc3b8447'),
    ('정약용유적지',            'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=ade5ce5f-f920-48b8-a8b5-0fc4b5b7b6ef'),
    ('죽주산성',                'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=586ffc18-c282-4c12-99b6-864249b77cf3'),
    ('중명전',                  'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=063404ac-8425-4830-91ed-75f3608ab646'),
    ('처인성',                  'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=1b624147-38ab-40e7-95b5-a4726c329bc3'),
    ('천진암 성지',             'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=fa8c0500-23df-4213-986b-982d80d12136'),
    ('최순우 옛집',             'http://www.ntculture.or.kr/culturalHeritage/1'),
    ('캠프 그리브스',           'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=747ab116-9f25-4a1b-975a-4db70b0cafe9'),
    ('탑골공원 팔각정',         'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=18e11d92-cede-4af7-9447-7eb6270168d3'),
    ('통일공원(파주)',           'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=5b8cfe60-3c7f-4cc5-b01a-4f85505ce813'),
    ('파주 이이 유적',          'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=c6a9a285-f2fe-4972-aecb-82a18148abb5'),
    ('판문점',                  'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=47338d24-dbee-4b54-b940-8c75c0a1c033'),
    ('팔달문',                  'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=7599459b-4eb9-41eb-8f27-1767ac7e0ab3'),
    ('황희선생유적지',          'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=2818a2e3-5192-4d45-b744-e58d3a98ab5d'),
    ('화성 제암리',             'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=be6239ac-4201-47d8-a2d9-d6692edc9188'),
    ('양화진외국인선교사묘원',  'https://yanghwajin.net/'),
    ('은이성지',                'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=30864ebe-e68c-469c-ad95-92c6050fd62c'),
    ('안성성당',                'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=ec644af9-4255-42b1-9ce2-cd859a61cc1a'),
    ('이상의집',                'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=2f0f75d3-2bad-4500-9602-4b0bfc82d0ab'),
    ('수원향교',                'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=cb5e957a-965f-4f16-807a-f331890f5f20'),
    # ── 향교 (한국민족문화대백과) ─────────────────────────────────
    ('과천향교',    'https://encykorea.aks.ac.kr/Article/E0004621'),
    ('광주향교',    'https://encykorea.aks.ac.kr/Article/E0005302'),
    ('김포향교',    'https://encykorea.aks.ac.kr/Article/E0010903'),
    ('남양향교',    'https://encykorea.aks.ac.kr/Article/E0012014'),
    ('양성향교',    'https://encykorea.aks.ac.kr/Article/E0035613'),
    ('양주향교',    'https://encykorea.aks.ac.kr/Article/E0035771'),
    ('여주향교',    'https://encykorea.aks.ac.kr/Article/E0036507'),
    ('용인향교',    'https://encykorea.aks.ac.kr/Article/E0005867'),
    ('진위향교',    'https://encykorea.aks.ac.kr/Article/E0054835'),
    ('평택향교',    'https://encykorea.aks.ac.kr/Article/E0060087'),
    # ── 서원·사우 (한국민족문화대백과) ───────────────────────────
    ('노강서원',    'https://encykorea.aks.ac.kr/Article/E0012629'),
    ('덕봉서원',    'https://encykorea.aks.ac.kr/Article/E0015338'),
    ('설봉서원',    'https://encykorea.aks.ac.kr/Article/E0029027'),
    ('심곡서원',    'https://encykorea.aks.ac.kr/Article/E0033733'),
    ('충렬서원',    'https://encykorea.aks.ac.kr/Article/E0058127'),
    ('우저서원',    'https://encykorea.aks.ac.kr/Article/E0040085'),
    ('궐리사',      'https://encykorea.aks.ac.kr/Article/E0038311'),
    ('파산서원',    'https://encykorea.aks.ac.kr/Article/E0059569'),
    # ── 역사유적 (한국민족문화대백과) ────────────────────────────
    ('권율장군묘',         'https://encykorea.aks.ac.kr/Article/E0007023'),
    ('정몽주선생묘',       'https://encykorea.aks.ac.kr/Article/E0050191'),
    ('최영장군묘',         'https://encykorea.aks.ac.kr/Article/E0057478'),
    ('창의문',             'https://encykorea.aks.ac.kr/Article/E0055516'),
    ('홍지문 및 탕춘대성', 'https://encykorea.aks.ac.kr/Article/E0064435'),
    ('호암산성',           'https://encykorea.aks.ac.kr/Article/E0061859'),
    ('하남 이성산성',      'https://encykorea.aks.ac.kr/Article/E0044732'),
]


class Command(BaseCommand):
    help = '공식 홈페이지 URL을 Place.website에 저장합니다'

    def add_arguments(self, parser):
        parser.add_argument('--overwrite', action='store_true',
                            help='이미 website가 있는 장소도 덮어쓰기')

    def handle(self, *args, **options):
        overwrite = options['overwrite']
        updated = skipped = 0

        for keyword, url in WEBSITE_MAP:
            qs = Place.objects.filter(name__icontains=keyword)
            if not overwrite:
                qs = qs.filter(website='')
            count = qs.update(website=url)
            if count:
                self.stdout.write(f'  [{count}건] {keyword} → {url}')
                updated += count
            else:
                skipped += 1

        self.stdout.write(self.style.SUCCESS(
            f'\n완료: {updated}개 업데이트, {skipped}개 키워드 미매칭'
        ))
